version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: Release build
          command: |
            ./gradlew assembleRelease;

      - run:
          name: Debug build
          command: |
            ./gradlew assembleDebug;

      - run:
          name: Install fastlane
          command: bundle install

      - run:
          name: Install fastlane plugin
          command: echo y | bundle exec fastlane add_plugin firebase_app_distribution

      - run:
          name: Install firebase
          command: |
            curl -sL firebase.tools | bash

      - run:
          name: upload release apk
          command: bundle exec fastlane deploy_aab_to_firebase apk_path:"/home/circleci/project/app/build/outputs/apk/release/app-release.apk" app_id:$FIREBASE_APP_ID firebase_token:$FIREBASE_TOKEN release_notes:"release版"

      - run:
          name: upload debug apk
          command: bundle exec fastlane deploy_aab_to_firebase apk_path:"/home/circleci/project/app/build/outputs/apk/debug/app-debug.apk" app_id:$FIREBASE_APP_ID firebase_token:$FIREBASE_TOKEN release_notes:"debug版"


workflows:
  sample:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
