version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: Release build
          command: |
            ./gradlew assembleRelease;

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.aab

      - run:
          name: Install fastlane
          command: bundle install

      - run:
          name: Install fastlane plugin
          command: echo y | bundle exec fastlane add_plugin firebase_app_distribution

      - run:
          name: Install firebase
          command: |
            curl -sL firebase.tools | bash

      - run:
          name: upload
          command: bundle exec fastlane deploy_aab_to_firebase branch:master app_id:$FIREBASE_APP_ID firebase_token:$FIREBASE_TOKEN


workflows:
  sample:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
