version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: Release build
          command: |
            ./gradlew bundleRelease;
          working_directory: TestAndroid

      - store_artifacts:
          path: app/build/outputs/bundle/release/app-release.aab
          destination: app-release.aab

      - run:
          name: Install fastlane
          command: bundle install
          working_directory: TestAndroid

      - run:
          name: Install firebase
          command: |
            curl -sL firebase.tools | bash
          working_directory: TestAndroid

      - run:
          name: upload
          command: bundle exec fastlane deploy_aab_to_firebase branch:master app_id:$FIREBASE_APP_ID firebase_token:$FIREBASE_TOKEN
          working_directory: TestAndroid


workflows:
  sample:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
