# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :deploy_aab_to_firebase do |options|
    firebase_app_distribution(
      app: "#{options[:app_id]}",
      apk_path: "app/build/outputs/bundle/release/app-release.aab",
      firebase_cli_token: "#{options[:firebase_token]}"
    )
  end
end
